### ISSUE TITLE
求帮助

### ISSUE THREAD

**Issue by liangcongBLC** [ShenHongFei/utorrent-block-xunlei#11]
D:\uTorrentBlockXunlei>nodejs\node.exe utorrent.js
(node:11900) UnhandledPromiseRejectionWarning: StatusCodeError: 401 - ""
    at new StatusCodeError (D:\uTorrentBlockXunlei\node_modules\request-promise-native\node_modules\request-promise-core\lib\errors.js:32:15)
    at Request.plumbing.callback (D:\uTorrentBlockXunlei\node_modules\request-promise-native\node_modules\request-promise-core\lib\plumbing.js:104:33)
    at Request.RP$callback [as _callback] (D:\uTorrentBlockXunlei\node_modules\request-promise-native\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at Request.self.callback (D:\uTorrentBlockXunlei\node_modules\request\request.js:185:28)
    at Request.emit (events.js:189:13)
    at Request.<anonymous> (D:\uTorrentBlockXunlei\node_modules\request\request.js:1161:14)
    at Request.emit (events.js:189:13)
    at IncomingMessage.<anonymous> (D:\uTorrentBlockXunlei\node_modules\request\request.js:1083:18)
    at Object.onceWrapper (events.js:277:13)
    at IncomingMessage.emit (events.js:194:15)
(node:11900) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:11900) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

D:\uTorrentBlockXunlei>pause
请按任意键继续. . .
这个问题如何解决呀？是我下载出问题了吗？

**Comment by ShenHongFei** [comment]
大概率是网络连接失败了，可能是端口设置错了，或者用户名密码输错了

**Comment by ShenHongFei** [comment]
@liangcongBLC  utorrent-block-xunlei-v2.0 正式发布！快来试试 v2.0 版本 [https://github.com/ShenHongFei/utorrent-block-xunlei/releases](https://github.com/ShenHongFei/utorrent-block-xunlei/releases)
